# Importing the libraries

In [1]:
import numpy as np
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Importing the dataset

In [3]:
data = pd.read_csv("/content/drive/MyDrive/Preprocessing/Data.csv")
data.head()

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    10 non-null     object
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object
dtypes: float64(2), object(2)
memory usage: 452.0+ bytes

In [6]:
data.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [8]:
data

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

# Fill Missing data

In [34]:
data["Age"].fillna(data["Age"].mean(), inplace=True)
data

/tmp/ipython-input-4052983135.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Age"].fillna(data["Age"].mean(), inplace=True)

   Country        Age   Salary Purchased
0   France  44.000000  72000.0        No
1    Spain  27.000000  48000.0       Yes
2  Germany  30.000000  54000.0        No
3    Spain  38.000000  61000.0        No
5   France  35.000000  58000.0       Yes
6    Spain  38.777778  52000.0        No
7   France  48.000000  79000.0       Yes
8  Germany  50.000000  83000.0        No
9   France  37.000000  67000.0       Yes

In [35]:
data.dropna(inplace=True, subset=['Salary'])
data

   Country        Age   Salary Purchased
0   France  44.000000  72000.0        No
1    Spain  27.000000  48000.0       Yes
2  Germany  30.000000  54000.0        No
3    Spain  38.000000  61000.0        No
5   France  35.000000  58000.0       Yes
6    Spain  38.777778  52000.0        No
7   France  48.000000  79000.0       Yes
8  Germany  50.000000  83000.0        No
9   France  37.000000  67000.0       Yes

#  Encoding categorical data

In [36]:
X = data.iloc[:, :-1]
Y = data.iloc[:, -1]

In [37]:
X

   Country        Age   Salary
0   France  44.000000  72000.0
1    Spain  27.000000  48000.0
2  Germany  30.000000  54000.0
3    Spain  38.000000  61000.0
5   France  35.000000  58000.0
6    Spain  38.777778  52000.0
7   France  48.000000  79000.0
8  Germany  50.000000  83000.0
9   France  37.000000  67000.0

In [38]:
X = pd.get_dummies(X, dtype=int)
X

         Age   Salary  Country_France  Country_Germany  Country_Spain
0  44.000000  72000.0               1                0              0
1  27.000000  48000.0               0                0              1
2  30.000000  54000.0               0                1              0
3  38.000000  61000.0               0                0              1
5  35.000000  58000.0               1                0              0
6  38.777778  52000.0               0                0              1
7  48.000000  79000.0               1                0              0
8  50.000000  83000.0               0                1              0
9  37.000000  67000.0               1                0              0

In [39]:
Y = (Y == "Yes").astype(int)

In [40]:
Y

0    0
1    1
2    0
3    0
5    1
6    0
7    1
8    0
9    1
Name: Purchased, dtype: int64

# Splitting the dataset into the Training set and Test set

In [41]:
from sklearn.model_selection import train_test_split

In [42]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

In [43]:
print(f"Shape of Train set: {X_train.shape}")
print(f"Shape of Test set: {X_test.shape}")

Shape of Train set: (7, 5)
Shape of Test set: (2, 5)

# Feature Scaling

In [44]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [45]:
sc = StandardScaler()
mm = MinMaxScaler()

In [56]:
X_train

    Age   Salary  Country_France  Country_Germany  Country_Spain
7  48.0  79000.0               1                0              0
3  38.0  61000.0               0                0              1
8  50.0  83000.0               0                1              0
5  35.0  58000.0               1                0              0
1  27.0  48000.0               0                0              1
9  37.0  67000.0               1                0              0
0  44.0  72000.0               1                0              0

In [58]:
X_train.describe()

             Age        Salary  Country_France  Country_Germany  Country_Spain
count   7.000000      7.000000        7.000000         7.000000       7.000000
mean   39.857143  66857.142857        0.571429         0.142857       0.285714
std     8.029707  12266.873704        0.534522         0.377964       0.487950
min    27.000000  48000.000000        0.000000         0.000000       0.000000
25%    36.000000  59500.000000        0.000000         0.000000       0.000000
50%    38.000000  67000.000000        1.000000         0.000000       0.000000
75%    46.000000  75500.000000        1.000000         0.000000       0.500000
max    50.000000  83000.000000        1.000000         1.000000       1.000000

In [61]:
sc_X_train = sc.fit_transform(X_train)
sc_X_train = pd.DataFrame(sc_X_train, columns=X_train.columns, index=X_train.index)
sc_X_train

        Age    Salary  Country_France  Country_Germany  Country_Spain
7  1.095344  1.069204        0.866025        -0.408248      -0.632456
3 -0.249815 -0.515733       -1.154701        -0.408248       1.581139
8  1.364376  1.421412       -1.154701         2.449490      -0.632456
5 -0.653363 -0.779890        0.866025        -0.408248      -0.632456
1 -1.729490 -1.660410       -1.154701        -0.408248       1.581139
9 -0.384331  0.012579        0.866025        -0.408248      -0.632456
0  0.557280  0.452839        0.866025        -0.408248      -0.632456

In [70]:
sc_X_train.describe()

,Age,Salary,Country_France,Country_Germany,Country_Spain
count,7.000000e+00,7.000000e+00,7.000000e+00,7.000000e+00,7.000000e+00
mean,3.965082e-16,2.061843e-16,9.516197e-17,6.344132e-17,3.172066e-17
std,1.080123e+00,1.080123e+00,1.080123e+00,1.080123e+00,1.080123e+00
min,-1.729490e+00,-1.660410e+00,-1.154701e+00,-4.082483e-01,-6.324555e-01
25%,-5.188471e-01,-6.478116e-01,-1.154701e+00,-4.082483e-01,-6.324555e-01
50%,-2.498153e-01,1.257887e-02,8.660254e-01,-4.082483e-01,-6.324555e-01
75%,8.263121e-01,7.610213e-01,8.660254e-01,-4.082483e-01,4.743416e-01
max,1.364376e+00,1.421412e+00,8.660254e-01,2.449490e+00,1.581139e+00

In [67]:
# Example
num = X_train.iloc[0, 0]
mean = X_train["Age"].mean()
std = X_train["Age"].std()
norm_num = (num - mean) / std
print(f"Original: {num}, Normalized: {norm_num}")

Original: 48.0, Normalized: 1.01409147274177

In [69]:
mm_X_train = mm.fit_transform(X_train)
mm_X_train = pd.DataFrame(mm_X_train, columns=X_train.columns, index=X_train.index)
mm_X_train

        Age    Salary  Country_France  Country_Germany  Country_Spain
7  0.913043  0.885714             1.0              0.0            0.0
3  0.478261  0.371429             0.0              0.0            1.0
8  1.000000  1.000000             0.0              1.0            0.0
5  0.347826  0.285714             1.0              0.0            0.0
1  0.000000  0.000000             0.0              0.0            1.0
9  0.434783  0.542857             1.0              0.0            0.0
0  0.739130  0.685714             1.0              0.0            0.0

In [71]:
mm_X_train.describe()

            Age    Salary  Country_France  Country_Germany  Country_Spain
count  7.000000  7.000000        7.000000         7.000000       7.000000
mean   0.559006  0.538776        0.571429         0.142857       0.285714
std    0.349118  0.350482        0.534522         0.377964       0.487950
min    0.000000  0.000000        0.000000         0.000000       0.000000
25%    0.391304  0.328571        0.000000         0.000000       0.000000
50%    0.478261  0.542857        1.000000         0.000000       0.000000
75%    0.826087  0.785714        1.000000         0.000000       0.500000
max    1.000000  1.000000        1.000000         1.000000       1.000000

In [73]:
# Example
num = X_train.iloc[0,0]
max = X_train["Age"].max()
min = X_train["Age"].min()
norm_num = (num - min) / (max - min)
print(f"Original: {num}, Normalized: {norm_num}")

Original: 48.0, Normalized: 0.9130434782608695