In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import scipy.stats as stats

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
data = pd.read_csv("/content/drive/MyDrive/Statistics/WA_Fn-UseC_-HR-Employee-Attrition.csv")
data.head(10)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
5,32,No,Travel_Frequently,1005,Research & Development,2,2,Life Sciences,1,8,...,3,80,0,8,2,2,7,7,3,6
6,59,No,Travel_Rarely,1324,Research & Development,3,3,Medical,1,10,...,1,80,3,12,3,2,1,0,0,0
7,30,No,Travel_Rarely,1358,Research & Development,24,1,Life Sciences,1,11,...,2,80,1,1,2,3,1,0,0,0
8,38,No,Travel_Frequently,216,Research & Development,23,3,Life Sciences,1,12,...,2,80,0,10,2,3,9,7,1,8
9,36,No,Travel_Rarely,1299,Research & Development,27,3,Medical,1,13,...,2,80,2,17,3,2,7,7,7,7

In [4]:
data.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,...,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,802.485714,9.192517,2.912925,1.0,1024.865306,2.721769,65.891156,2.729932,2.063946,...,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,403.509100,8.106864,1.024165,0.0,602.024335,1.093082,20.329428,0.711561,1.106940,...,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,491.250000,2.000000,48.000000,2.000000,1.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,802.000000,7.000000,3.000000,1.0,1020.500000,3.000000,66.000000,3.000000,2.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1555.750000,4.000000,83.750000,3.000000,3.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [5]:
data.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [6]:
data["Attrition"].value_counts()

Attrition
No     1233
Yes     237
Name: count, dtype: int64

In [7]:
data["JobSatisfaction"].value_counts()

JobSatisfaction
4    459
3    442
1    289
2    280
Name: count, dtype: int64

In [8]:
ct = pd.crosstab(data["Attrition"], data["JobSatisfaction"], margins=True)
ct

JobSatisfaction    1    2    3    4   All
Attrition
No               223  234  369  407  1233
Yes               66   46   73   52   237
All              289  280  442  459  1470

In [9]:
obs = np.append(ct.iloc[0][: -1].values, ct.iloc[1][: -1].values)
obs

array([223, 234, 369, 407,  66,  46,  73,  52])

In [10]:
no = ct.iloc[0]/ct.iloc[0,-1]
no

JobSatisfaction
1      0.180860
2      0.189781
3      0.299270
4      0.330089
All    1.000000
Name: No, dtype: float64

In [11]:
yes = ct.iloc[1]/ct.iloc[1,-1]
yes

JobSatisfaction
1      0.278481
2      0.194093
3      0.308017
4      0.219409
All    1.000000
Name: Yes, dtype: float64

In [12]:
diff = no - yes
diff

JobSatisfaction
1     -0.097621
2     -0.004312
3     -0.008747
4      0.110680
All    0.000000
dtype: float64

In [13]:
row_sum = ct.iloc[:2,-1].values
row_sum

array([1233,  237])

In [14]:
total = row_sum.sum()
total

np.int64(1470)

In [15]:
exp = []
for j in range(2):
  for val in ct.iloc[2, : -1].values:
    print(val, "*", row_sum[j], "/", total, "=", val*row_sum[j]/total)
    exp.append(val*row_sum[j]/total)

289 * 1233 / 1470 = 242.4061224489796
280 * 1233 / 1470 = 234.85714285714286
442 * 1233 / 1470 = 370.7387755102041
459 * 1233 / 1470 = 384.99795918367346
289 * 237 / 1470 = 46.593877551020405
280 * 237 / 1470 = 45.142857142857146
442 * 237 / 1470 = 71.26122448979592
459 * 237 / 1470 = 74.00204081632653

In [36]:
chi2_formula = ((obs - exp)**2 / exp).sum()
chi2_formula

np.float64(17.505077010348)

In [21]:
dof = (len(row_sum)- 1)*(len(ct.iloc[2,:-1])-1)
dof

3






<html>
<body>

<img src="https://www.scribbr.com/wp-content/uploads/2022/05/chi-square-distribution-table.png" alt="Chi2-Test">

</body>
</html>

In [27]:
# Table: alpha = 0.05, df = 3
chi2_table = 7.815

if chi2_formula > chi2_table:
    print("Reject H0")
else:
    print("Accept H0")

Reject H0

In [26]:
chi2_cdf = 1 - stats.chi2.cdf(chi2_formula, dof)

if chi2_cdf < 0.05:
  print("Reject H0")

Reject H0

Based on the Chi-square test results (p < 0.05), there is a statistically significant relationship between job satisfaction and attrition.

In [28]:
ct

JobSatisfaction    1    2    3    4   All
Attrition
No               223  234  369  407  1233
Yes               66   46   73   52   237
All              289  280  442  459  1470

In [30]:
data_array = ct.iloc[:2,:-1].values
data_array

array([[223, 234, 369, 407],
       [ 66,  46,  73,  52]])

In [39]:
# JobSatisfaction vs Attrition
chi2, p_value, dof, expected = stats.chi2_contingency(data_array)
print("Chi-square statistic:", chi2)
print("p-value:", p_value)
print("Degrees of freedom:", dof)
print("Expected frequencies:\n", expected)

Chi-square statistic: 17.505077010348
p-value: 0.0005563004510387556
Degrees of freedom: 3
Expected frequencies:
 [[242.40612245 234.85714286 370.73877551 384.99795918]
 [ 46.59387755  45.14285714  71.26122449  74.00204082]]

In [40]:
expected.sum()

np.float64(1470.0)

In [41]:
from scipy.stats import chisquare
chisquare(data_array)

Power_divergenceResult(statistic=array([ 85.29065744, 126.22857143, 198.22624434, 274.56427015]), pvalue=array([2.57577384e-20, 2.74031376e-29, 5.09229443e-45, 1.14862090e-61]))

In [42]:
# Attrition and Education
ct2 = pd.crosstab(data["Attrition"], data["Education"], margins=True)
ct2
#

Education    1    2    3    4   5   All
Attrition
No         139  238  473  340  43  1233
Yes         31   44   99   58   5   237
All        170  282  572  398  48  1470

In [43]:
data_array2 = ct2.iloc[:2,:-1].values
data_array2

array([[139, 238, 473, 340,  43],
       [ 31,  44,  99,  58,   5]])

In [44]:
chi2, p_value, dof, expected = stats.chi2_contingency(data_array2)
print("Chi-square statistic:", chi2)
print("p-value:", p_value)
print("Degrees of freedom:", dof)
print("Expected frequencies:\n", expected)

Chi-square statistic: 3.0739613982367193
p-value: 0.5455253376565949
Degrees of freedom: 4
Expected frequencies:
 [[142.59183673 236.53469388 479.77959184 333.83265306  40.26122449]
 [ 27.40816327  45.46530612  92.22040816  64.16734694   7.73877551]]

Based on the Chi-square test results (p > 0.05), there is no statistically significant relationship between education and attrition.