In [1]:
from scipy import stats
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from warnings import filterwarnings
filterwarnings('ignore')

In [2]:
g1 = [20, 23, 21, 25, 18, 17, 18, 24, 20, 24, 23, 19]
g2 = [24, 25, 21, 22, 23, 28, 24, 27, 21, 23]

In [3]:
g1_df = pd.DataFrame(g1, columns=["number"])
g2_df = pd.DataFrame(g2, columns=["number"])

In [8]:
print("Describe of g1")
g1_df.describe()

Describe of g1

          number
count  12.000000
mean   21.000000
std     2.730301
min    17.000000
25%    18.750000
50%    20.500000
75%    23.250000
max    25.000000

In [9]:
print("Describe of g2")
g2_df.describe()

Describe of g2

          number
count  10.000000
mean   23.800000
std     2.347576
min    21.000000
25%    22.250000
50%    23.500000
75%    24.750000
max    28.000000

In [10]:
g1_df["group"] = "g1"
g2_df["group"] = "g2"
g2_df

   number group
0      24    g2
1      25    g2
2      21    g2
3      22    g2
4      23    g2
5      28    g2
6      24    g2
7      27    g2
8      21    g2
9      23    g2

In [22]:
# Merge two Data Frame
merge_df = g1_df.merge(g2_df, on = ["number", 'group'], how="outer" )

In [23]:
merge_df.sort_values("number").reset_index(drop=True)
merge_df.index = merge_df.index + 1
merge_df

    number group
1       17    g1
2       18    g1
3       18    g1
4       19    g1
5       20    g1
6       20    g1
7       21    g1
8       21    g2
9       21    g2
10      22    g2
11      23    g1
12      23    g1
13      23    g2
14      23    g2
15      24    g1
16      24    g1
17      24    g2
18      24    g2
19      25    g1
20      25    g2
21      27    g2
22      28    g2

In [50]:
merge_df["rank"] = stats.rankdata(merge_df["number"], method="average")
merge_df

    number group  rank
1       17    g1   1.0
2       18    g1   2.5
3       18    g1   2.5
4       19    g1   4.0
5       20    g1   5.5
6       20    g1   5.5
7       21    g1   8.0
8       21    g2   8.0
9       21    g2   8.0
10      22    g2  10.0
11      23    g1  12.5
12      23    g1  12.5
13      23    g2  12.5
14      23    g2  12.5
15      24    g1  16.5
16      24    g1  16.5
17      24    g2  16.5
18      24    g2  16.5
19      25    g1  19.5
20      25    g2  19.5
21      27    g2  21.0
22      28    g2  22.0

In [51]:
R1 = merge_df.loc[merge_df['group'] == "g1"]["rank"].to_numpy().sum()
R2 = merge_df.loc[merge_df['group'] == "g2"]["rank"].to_numpy().sum()
n1 = len(g1)
n2 = len(g2)

print("R1: ", R1)
print("R2: ", R2)
print("n1: ", n1)
print("n2: ", n2)

R1:  106.5
R2:  146.5
n1:  12
n2:  10

In [53]:
U1 = R1 - (n1*(n1+1)/2)
U2 = R2 - (n2*(n2+1)/2)
Uf = min(U1, U2)

print("U1:", U1)
print("U2:", U2)
print("U (final):", Uf)

U1: 28.5
U2: 91.5
U (final): 28.5

In [54]:
print(U1 + U2 == n1 * n2)

True

In [55]:
mean = (n1 * n2) / 2
print("Mean: ", mean)

std = np.sqrt(n1 * n2 * (n1 + n2 + 1) / 12)
print("Std: ", std)

Mean:  60.0
Std:  15.165750888103101

In [73]:
Z_score = (Uf - mean) / std
print("Z_score: ", Z_score)

Z_score:  -2.077048491196729

In [74]:
# Two Sided
Z_score_table = 0.01876*2
print(f"p_value: {Z_score_table}")

p_value: 0.03752

In [75]:
U_formula, p_value = stats.mannwhitneyu(g1, g2, alternative="two-sided")
print("U_formula: ", U_formula)
print("p_value: ", p_value)

U_formula:  28.5
p_value:  0.039413690126797137

In [76]:
# g1 greater than g2
Z_score_table = 1 - 0.01876
print(f"p_value: {Z_score_table}")

p_value: 0.98124

In [77]:
U_formula, p_value = stats.mannwhitneyu(g1, g2, alternative="greater")
print("U_formula: ", U_formula)
print("p_value: ", p_value)

U_formula:  28.5
p_value:  0.9832603592232242

In [78]:
# g1 less than g2
Z_score_table =  0.01876
print(f"p_value: {Z_score_table}")

p_value: 0.01876

In [79]:
U_formula, p_value = stats.mannwhitneyu(g1, g2, alternative="less")
print("U_formula: ", U_formula)
print("p_value: ", p_value)

U_formula:  28.5
p_value:  0.019706845063398568